### ISSUE TITLE
Feature Request: 1.10.2 Support

### ISSUE THREAD

**Issue by kriNon** [asiekierka/endernet#9]
Hey,
I was wondering if you had any plans to update this mod to 1.10.2?
I am working on a modpack which relies heavily on the idea of cross server item transfer, and it doesn't seem like anything of the sort exists for 1.10.2.

Thanks!

**Comment by asiekierka** [comment]
Ideas? Yes. Plans? No, I'm afraid.

2016-12-26 8:04 GMT+01:00 kriNon <notifications@github.com>:

**Comment by kriNon** [comment]
Sorry, what do you mean by that?
Do you mean that you have ideas but no plan to act upon them, or do you mean that you plan to create something with similar functionality, but not "endernet"?

**Comment by asiekierka** [comment]
Ideas but no plan to act upon them. Apologies for the inconvienence - I
have other mod projects as well...

2016-12-26 10:11 GMT+01:00 kriNon <notifications@github.com>:

**Comment by kriNon** [comment]
Yeah, no worries. Thanks anyway and good luck with your other projects!

**Comment by kriNon** [comment]
Hey, quick question. With the current license of this project, is it okay to try to update it and release it?
My thoughts are that while I probably can't make something like this from scratch, I could probably do it if I was to copy and edit it.

**Comment by asiekierka** [comment]
Do read the license, it's fairly short.

**Comment by DaMatrix** [comment]
@kriNon https://tldrlegal.com/license/mit-license

**Comment by asiekierka** [comment]
Already resolved elsewhere.
